"""Browsable HTML viewer for the merged 500-sample annotation file.

Reads data/newsclippings/annotations_500.csv (run make_annotations_500.py
first) plus each packet's pilot_samples.json (for the image's original
caption), and writes data/newsclippings/annotations_500.html — a single
self-contained page. Images are referenced relatively into the packet
subdirectories (pilot_seed42/, formal_seed43/), so the page works by
double-clicking it (file://) as long as it stays in data/newsclippings/.

Run from the project root:
    python3 scripts/make_annotations_500_html.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
BASE = PROJECT_ROOT / "data" / "newsclippings"
PACKETS = ["pilot_seed42", "formal_seed43"]
CSV_IN = BASE / "annotations_500.csv"
OUT = BASE / "annotations_500.html"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>NewsCLIPpings 500-sample annotations</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
         margin: 0; background: #f5f6f8; color: #1a1a1a; }
  header { position: sticky; top: 0; z-index: 5; background: #fff;
           border-bottom: 1px solid #ddd; padding: 10px 16px; }
  h1 { font-size: 17px; margin: 0 0 8px; }
  .controls { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }
  .controls select, .controls input {
    padding: 5px 8px; border: 1px solid #ccc; border-radius: 6px;
    font-size: 13px; background: #fff; }
  .controls input { width: 240px; }
  #count { font-size: 13px; color: #555; margin-left: auto; }
  main { max-width: 1080px; margin: 0 auto; padding: 14px; }
  .card { display: flex; gap: 14px; background: #fff; border: 1px solid #e2e2e2;
          border-radius: 10px; padding: 12px; margin-bottom: 12px; }
  .card img { width: 220px; height: 165px; object-fit: cover;
              border-radius: 6px; background: #eee; flex: none; }
  .meta { min-width: 0; }
  .badges { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 6px; }
  .b { font-size: 11.5px; padding: 2px 8px; border-radius: 10px;
       background: #eef0f3; color: #444; white-space: nowrap; }
  .b.id { background: #1a1a1a; color: #fff; }
  .b.rel-entailment { background: #dcefdc; color: #1e6b1e; }
  .b.rel-neutral { background: #e8e8e8; color: #555; }
  .b.rel-contradiction { background: #f7dcdc; color: #a02020; }
  .b.ver-falsified { background: #fdeeda; color: #8a5a00; }
  .b.ver-pristine { background: #e3edf8; color: #22568c; }
  .cap { font-size: 14px; margin: 4px 0; }
  .orig { font-size: 13px; color: #666; margin: 4px 0; }
  .orig b { color: #444; }
  .notes { font-size: 13px; color: #333; background: #f8f8f4;
           border-left: 3px solid #d8d3b8; padding: 6px 10px;
           border-radius: 0 6px 6px 0; margin-top: 6px; }
  footer { text-align: center; color: #888; font-size: 12px; padding: 18px; }
</style>
</head>
<body>
<header>
  <h1>NewsCLIPpings two-layer annotations — 500 samples
      <span style="font-weight:normal;color:#777">(pilot 200 + formal 300;
      notes are the plain-English rewrite)</span></h1>
  <div class="controls">
    <select id="f-ver"><option value="">veracity: all</option>
      <option>pristine</option><option>falsified</option></select>
    <select id="f-rel"><option value="">relation: all</option>
      <option>entailment</option><option>neutral</option>
      <option>contradiction</option></select>
    <select id="f-chan"><option value="">channel: all</option>
      <option>visible_conflict</option><option>event_provenance</option>
      <option>external_knowledge</option><option>temporal_provenance</option>
      <option>other</option><option>n/a</option></select>
    <select id="f-packet"><option value="">packet: all</option>
      <option>pilot_seed42</option><option>formal_seed43</option></select>
    <input id="f-q" type="search"
           placeholder="search caption / notes / sample id">
    <span id="count"></span>
  </div>
</header>
<main id="list"></main>
<footer>Generated by scripts/make_annotations_500_html.py — images load from
the packet folders; keep this file inside data/newsclippings/.</footer>
<script>
const DATA = __DATA__;
const list = document.getElementById("list");
const count = document.getElementById("count");
const els = {ver: f("f-ver"), rel: f("f-rel"), chan: f("f-chan"),
             packet: f("f-packet"), q: f("f-q")};
function f(id) { return document.getElementById(id); }
function esc(s) { return s.replace(/&/g, "&amp;").replace(/</g, "&lt;"); }
function card(d) {
  const img = d.packet + "/full/" + d.file;
  const th = d.packet + "/thumbnails/" + d.file;
  return `<div class="card">
    <a href="${img}" target="_blank"><img loading="lazy" src="${th}"
       alt="sample ${d.id}"></a>
    <div class="meta">
      <div class="badges">
        <span class="b id">#${d.id}</span>
        <span class="b ver-${d.ver}">${d.ver}</span>
        <span class="b rel-${d.rel}">${d.rel}</span>
        ${d.chan === "n/a" ? "" :
          `<span class="b">channel: ${d.chan}</span>`}
        <span class="b">confidence: ${d.conf}</span>
        <span class="b">${d.split}</span>
        <span class="b">${d.packet}</span>
      </div>
      <div class="cap"><b>Caption:</b> ${esc(d.cap)}</div>
      ${d.ver === "falsified" ? `<div class="orig"><b>Image's original
        caption:</b> ${esc(d.orig)}</div>` : ""}
      <div class="notes">${esc(d.notes)}</div>
    </div>
  </div>`;
}
function render() {
  const q = els.q.value.trim().toLowerCase();
  const shown = DATA.filter(d =>
    (!els.ver.value || d.ver === els.ver.value) &&
    (!els.rel.value || d.rel === els.rel.value) &&
    (!els.chan.value || d.chan === els.chan.value) &&
    (!els.packet.value || d.packet === els.packet.value) &&
    (!q || String(d.id) === q || d.cap.toLowerCase().includes(q) ||
     d.notes.toLowerCase().includes(q)));
  list.innerHTML = shown.map(card).join("");
  count.textContent = shown.length + " / " + DATA.length + " shown";
}
Object.values(els).forEach(e => e.addEventListener("input", render));
render();
</script>
</body>
</html>
"""


def main() -> None:
    orig_caption = {}
    for p in PACKETS:
        for s in json.loads((BASE / p / "pilot_samples.json").read_text()):
            orig_caption[int(s["sample_id"])] = s.get("original_caption", "")

    data = []
    with CSV_IN.open(newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            sid = int(r["sample_id"])
            img = BASE / r["packet"] / "full" / f"{sid:03d}.jpg"
            if not img.exists():
                raise RuntimeError(f"missing image {img}")
            data.append({
                "id": sid, "packet": r["packet"], "file": f"{sid:03d}.jpg",
                "split": r["official_split"], "ver": r["veracity"],
                "cap": r["caption"], "rel": r["relation_label"],
                "chan": r["evidence_channel"],
                "conf": r["annotator_confidence"], "notes": r["notes"],
                "orig": orig_caption.get(sid, ""),
            })
    if len(data) != 500:
        raise RuntimeError(f"expected 500 rows, got {len(data)}")

    data.sort(key=lambda d: d["id"])
    html = TEMPLATE.replace("__DATA__", json.dumps(data, ensure_ascii=False))
    OUT.write_text(html, encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size / 1e6:.1f} MB, "
          f"{len(data)} cards)")


if __name__ == "__main__":
    main()
